<?php 
/*
 * SELECT DISTINCT KB_T.Target_id, KB_OP.OP_ID, KB_TS.TARGET_SERVICE_ID, KB_T.Target_Name, KB_T.TARGET_PUBLIC_NAME, KB_TS.SERVICE_TYPE, 
 L_OPI.LAST_UPDATE_DATE,
L_OPI.Activation_Status, KB_OP.Threshold
  FROM  sfxglb41.KB_TARGETS KB_T, 
	sfxglb41.KB_TARGET_SERVICES KB_TS , 
	sfxglb41.KB_OBJECT_PORTFOLIOS KB_OP,
	sfxlcl41.LCL_OBJECT_PORTFOLIO_INVENTORY L_OPI
	
 WHERE KB_TS.TARGET_ID=KB_T.TARGET_ID AND 
 	( KB_T.TARGET_ID IN (SELECT TARGET_ID FROM KB_OBJECT_PORTFOLIOS KB_OP WHERE OBJECT_ID='954925427238') 	
		AND L_OPI.OP_ID IN (SELECT OP_ID FROM KB_OBJECT_PORTFOLIOS KB_OP WHERE OBJECT_ID='954925427238')
		AND L_OPI.OP_ID = KB_OP.OP_ID
		AND KB_OP.TARGET_ID=KB_T.TARGET_ID
	  ) AND L_OPI.Activation_Status = 'ACTIVE' AND KB_TS.SERVICE_TYPE!='getTOC'
ORDER BY KB_T.TARGET_NAME
LIMIT 100
 */

include_once('config.inc.php');

?>


